### ISSUE TITLE
Missing Profile Picture for Mark

### ISSUE THREAD

**Issue by mangiaag** [idoideas/FaceZUCC#1]
The site providing Mark's profile picture is sending a 403 error. The link on line 1 of magicfunctions.js sends you to a page saying the url signature is expired. https://github.com/idoideas/FaceZUCC/blob/master/magicfunctions.js#L1

**Comment by idoideas** [comment]
Thank you for noticing and reporting! Fixed it with an Imgur replacement on commit 37f92dd53122e73d7c6e9c502bfd465f122cf616 .
